[package]
name = "v4l2-createimage-rs"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
bind-v4l2 = { path = "bind-v4l2", version = "0.1.0" }
libc = "0.2.142"

[workspace]
members = [
    "bind-v4l2",
]
